// <auto-generated />
using System;
using EMPLOYEE_ALL_ORGANIZATIONS_WITH_ENTITY;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMPLOYEE_ALL_ORGANIZATIONS_WITH_ENTITY.Migrations
{
    [DbContext(typeof(MakingConnection))]
    [Migration("20220621105445_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EMPLOYEE_ALL_ORGANIZATIONS_WITH_ENTITY.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"), 1L, 1);

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("EMPLOYEE_ALL_ORGANIZATIONS_WITH_ENTITY.Entities.EmployeeOrganization", b =>
                {
                    b.Property<int>("EmployeeOrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeOrganizationID"), 1L, 1);

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeOrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeOrganizationID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("employeeOrganizations");
                });

            modelBuilder.Entity("EMPLOYEE_ALL_ORGANIZATIONS_WITH_ENTITY.Entities.EmployeeOrganization", b =>
                {
                    b.HasOne("EMPLOYEE_ALL_ORGANIZATIONS_WITH_ENTITY.Entities.Employee", "employee")
                        .WithMany("EmployeeOrganizations")
                        .HasForeignKey("EmployeeID");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("EMPLOYEE_ALL_ORGANIZATIONS_WITH_ENTITY.Entities.Employee", b =>
                {
                    b.Navigation("EmployeeOrganizations");
                });
#pragma warning restore 612, 618
        }
    }
}
