CREATE TABLE PRODUCT(PID INT PRIMARY KEY, PNAME VARCHAR(50) UNIQUE,PRICE FLOAT)
CREATE TABLE SALES(SID INT PRIMARY KEY, PID INT, QUANTITY INT,TOTALCOST FLOAT,SALESDATE DATE,FOREIGN KEY(PID) REFERENCES PRODUCT(PID))

SELECT * FROM PRODUCT
SELECT * FROM SALES

DROP TABLE PRODUCT
DROP TABLE SALES 

delete from sales
delete from product